#!/usr/bin/env node
/**
 * Skill Auto-Discovery Sync Script
 *
 * Scans every skill.yaml under skills/ and generates canonical index files
 * for all supported AI agent ecosystems.
 *
 * Usage:
 *   node scripts/sync-skills.js
 *
 * Outputs:
 *   SKILLS_INDEX.yaml               — Canonical machine-readable index
 *   .agents/skills/skills-index.yaml — AI agent ecosystem index
 *   .claude/skills/skills-index.yaml — Claude Code index
 *   .opencode/skills/skills-index.yaml — OpenCode index
 */

import { readdir, readFile, writeFile, mkdir } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parse as parseYaml, stringify as stringifyYaml } from 'yaml';

const __dirname = dirname(fileURLToPath(import.meta.url));
const rootDir = join(__dirname, '..');
const skillsDir = join(rootDir, 'skills');

const agentDirs = [
  join(rootDir, '.agents', 'skills'),
  join(rootDir, '.claude', 'skills'),
  join(rootDir, '.opencode', 'skills'),
];

async function discoverSkills() {
  const entries = await readdir(skillsDir, { withFileTypes: true });
  const dirs = entries.filter((e) => e.isDirectory()).map((e) => e.name);

  const skills = [];
  for (const dir of dirs) {
    const yamlPath = join(skillsDir, dir, 'skill.yaml');
    try {
      const raw = await readFile(yamlPath, 'utf-8');
      const doc = parseYaml(raw);
      skills.push({
        name: doc.name || dir,
        version: doc.version || '1.0.0',
        description: (doc.description || '').replace(/\n+/g, ' ').trim().slice(0, 300),
        tags: doc.tags || [],
        categories: doc.categories || [],
        standards: (doc.standards || []).slice(0, 10),
        workflows: Object.keys(doc.workflows || {}),
        output_formats: (() => {
          const raw = doc.expected_outputs || doc.output_formats || [];
          if (Array.isArray(raw)) {
            return raw.map((o) => (typeof o === 'string' ? o : o.name || o.format));
          }
          if (raw && typeof raw === 'object') {
            return Object.keys(raw);
          }
          return [];
        })(),
        validation_rules: (doc.validation_rules || []).length,
        skill_path: `skills/${dir}/SKILL.md`,
        config_path: `skills/${dir}/skill.yaml`,
      });
    } catch (err) {
      console.warn(`  Warning: Could not parse ${yamlPath}: ${err.message}`);
    }
  }

  skills.sort((a, b) => a.name.localeCompare(b.name));
  return skills;
}

async function writeCanonicalIndex(skills) {
  const index = {
    version: '1.0.0',
    generated_at: new Date().toISOString(),
    total_skills: skills.length,
    skills: skills.map((s) => ({
      name: s.name,
      version: s.version,
      description: s.description,
      tags: s.tags,
      categories: s.categories,
      path: s.skill_path,
      config: s.config_path,
    })),
  };

  const outPath = join(rootDir, 'SKILLS_INDEX.yaml');
  await writeFile(outPath, stringifyYaml(index), 'utf-8');
  console.log(`  Written: ${outPath} (${skills.length} skills)`);
}

async function writeAgentIndices(skills) {
  const index = {
    version: '1.0.0',
    generated_at: new Date().toISOString(),
    note: 'Auto-generated by scripts/sync-skills.js — do not edit manually',
    discovery_instruction: 'Read this file on startup to discover all available skills in this repository.',
    total_skills: skills.length,
    skills: skills.map((s) => ({
      name: s.name,
      description: s.description,
      tags: s.tags,
      categories: s.categories,
      skill_file: s.skill_path,
      config_file: s.config_path,
    })),
  };

  for (const dir of agentDirs) {
    await mkdir(dir, { recursive: true });
    const outPath = join(dir, 'skills-index.yaml');
    await writeFile(outPath, stringifyYaml(index), 'utf-8');
    console.log(`  Written: ${outPath}`);
  }
}

async function writeMarkdownIndex(skills) {
  const lines = [
    '# Skills Index',
    '',
    `> Auto-generated index of ${skills.length} available skills.`,
    `> Last updated: ${new Date().toISOString()}`,
    '',
    '| Skill | Categories | Tags | File |',
    '|-------|------------|------|------|',
  ];

  for (const s of skills) {
    const cats = s.categories.join(', ') || '-';
    const tags = s.tags.slice(0, 5).join(', ') + (s.tags.length > 5 ? '...' : '') || '-';
    lines.push(
      `| **${s.name}** | ${cats} | ${tags} | [SKILL.md](${s.skill_path}) |`
    );
  }

  lines.push('');
  lines.push('## Usage');
  lines.push('');
  lines.push('To use a skill, read its `SKILL.md` file. Each skill contains:');
  lines.push('- A detailed system prompt defining the expert persona');
  lines.push('- Input/output schemas');
  lines.push('- Validation rules');
  lines.push('- Example workflows');
  lines.push('');
  lines.push('## Discovery');
  lines.push('');
  lines.push('Run the sync script to regenerate this index:');
  lines.push('```bash');
  lines.push('node scripts/sync-skills.js');
  lines.push('```');

  const outPath = join(rootDir, 'SKILLS_INDEX.md');
  await writeFile(outPath, lines.join('\n'), 'utf-8');
  console.log(`  Written: ${outPath}`);
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

console.log('Scanning skills...');
const skills = await discoverSkills();
console.log(`Discovered ${skills.length} skills.`);

console.log('\nGenerating index files...');
await writeCanonicalIndex(skills);
await writeAgentIndices(skills);
await writeMarkdownIndex(skills);

console.log('\nDone. All index files are in sync.');
